In [2]:
import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 8]])

## Linear Algebra

In [3]:
from scipy import linalgg

Determinant of matrix

In [5]:
linalg.det(A)

3.0

Compute pivoted LU decomposition of a matrix.

The decomposition is::

    A = P L U

where P is a permutation matrix, L lower triangular with unit
diagonal elements, and U upper triangular.

In [6]:
P, L, U = linalg.lu(A)

In [7]:
P

array([[ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.]])

In [8]:
L

array([[ 1.        ,  0.        ,  0.        ],
       [ 0.14285714,  1.        ,  0.        ],
       [ 0.57142857,  0.5       ,  1.        ]])

In [9]:
U

array([[ 7.        ,  8.        ,  8.        ],
       [ 0.        ,  0.85714286,  1.85714286],
       [ 0.        ,  0.        ,  0.5       ]])

In [10]:
np.dot(L, U)

array([[ 7.,  8.,  8.],
       [ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

We can find out the eigenvalues and eigenvectors of this matrix:

In [11]:
EW, EV = linalg.eig(A)

In [12]:
EW

array([ 15.55528261+0.j,  -1.41940876+0.j,  -0.13587385+0.j])

In [13]:
EV

array([[-0.24043423, -0.67468642,  0.51853459],
       [-0.54694322, -0.23391616, -0.78895962],
       [-0.80190056,  0.70005819,  0.32964312]])

Solving systems of linear equations can also be done:

In [14]:
v = np.array([[2], [3], [5]])

In [15]:
v

array([[2],
       [3],
       [5]])

In [16]:
s = linalg.solve(A, v)

In [17]:
s

array([[-2.33333333],
       [ 3.66666667],
       [-1.        ]])

## Sparse Linear Algebra
SciPy has some routines for computing with sparse and potentially very large matrices. The necessary tools are in the submodule scipy.sparse.

We make one example on how to construct a large matrix:

In [19]:
from scipy import sparse

In [20]:
A = sparse.lil_matrix((1000, 1000))

In [21]:
A

<1000x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 0 stored elements in LInked List format>

In [22]:
A[0, :100] = np.random.randn(100)

In [23]:
A[1, 100:200] = A[0, :100]

In [24]:
A.setdiag(np.random.randn(1000))

In [25]:
A

<1000x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 1199 stored elements in LInked List format>

**Linear Algebra for Sparse Matrices**

In [31]:
from scipy import linalg

In [32]:
A.tocsr()

<1000x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 1199 stored elements in Compressed Sparse Row format>

In [33]:
A = A.tocsr()

In [36]:
b = np.random.rand(1000)

In [37]:
linalg.spsolve(A, b)

AttributeError: module 'scipy.linalg' has no attribute 'spsolve'